### ISSUE TITLE
PTZ recall works but PTZ-Controll doesn‘t on CR-500N

### ISSUE THREAD

**Issue by roxolid-one** [bitfocus/companion-module-sony-visca#28]
Hi,
I have a Canon CR-500N.
I can connect to it‘s instance with companion and I can store and recall presets, however most other functions like pan or tilt, zoom and p/t-speed don’t seem to work.
I connect to the camera via vista protocol, wich works with other softwares (e.g. vMix), so the protocol can not be the issue.
Any ideas on how to solve this?
Thanks a lot!

**Comment by josephdadams** [comment]
There's a canon-ptz module now, so I will close this out since you can just use that module.
