### ISSUE TITLE
Custom Commands for SONY VISCA to set camera address

### ISSUE THREAD

**Issue by tonybeatle** [bitfocus/companion-module-sony-visca#31]
Is there a way to add custom commands to the sony visca module? I have my PTZ cameras daisy chained and I can only control the first camera until I plug in my old joystick and back to companion and all the cameras work. If I can send a custom command "88 30 01 FF" then it sets all the cameras address ID and I won't need my old joystick. Thanks

**Comment by BB21B** [comment]
Just to add, this is functionally the same as the ptzoptics-visca module Custom Command. 
Except the Regex needs to be changed to allow 8* currently it is limited to 81 in that module.

**Comment by tonybeatle** [comment]
Is there any update to adding custom commands or the command to set camera address to this module? Right now I still have to plug in my old controls to set the addresses then plug it back to the device I use for companion. Thanks

**Comment by josephdadams** [comment]
Can’t you just use the generic tcp UDP module to do this?

**Comment by tonybeatle** [comment]
I've tried using the same IP and port that work on the SONY module but Im not able to connect using the generic tcp UDP module. Am I missing something? Also the module has a setting for 'Command End Character', what setting should I use? Thanks

**Comment by goseid** [comment]
The custom command option has been implemented in Companion v3.0.0+5781 (beta). The implementation does allow any valid hex characters.

Please let us know if you are able to use the custom command to set the camera address. Feel free to close the issue if you are satisfied.

**Comment by tonybeatle** [comment]
I'm not able to test. 5781 doesn't have an intel Mac download yet. I will let you know if it works when there is a download. thanks

**Comment by tonybeatle** [comment]
I copied the set address code from the manual but its not working. The code is shorter than the other ones so the text is red and I think it thinks it not a full command. what am I missing? thanks

**Comment by RoseOO** [comment]
I was going to say pad it with some 00 but its been made as a regular expression. I would recommend the regex gets removed it is not really needed.

**Comment by tonybeatle** [comment]
I’m not sure what you mean by regular expression and regex. What would I need to do to get this command to work and address my cameras? Thanks On Jun 6, 2023, at 9:32 AM, RoseO ***@***.***> wrote:﻿
I was going to say pad it with some 00 but its been made as a regular expression. I would recommend the regex gets removed it is not really needed.
