### ISSUE TITLE
Recall Preset with variable number

### ISSUE THREAD

**Issue by bensteUEM** [bitfocus/companion-module-sony-visca#34]
I would like to use a variable to quickly shift through various numbers used as preset position.
However the Action only allows to select position 1-64 as a dropdown.

Is there a way to also allow the use of variables and e.g. MOD 64 them?

**Comment by goseid** [comment]
Can you expand on that? An example of your work flow and how the variable would be used may help me understand.

**Comment by bensteUEM** [comment]
Sure, let me provide some screenshots :)

![Screenshot from 2022-09-16 19-02-28](https://user-images.githubusercontent.com/6708590/190691611-1846d0e6-ab1f-48a8-956d-6008c23b6c16.png)
Usually the command set for calling or storing a preset is straight forward - one Button =  One Preset

I did create a companion internal variable (ideally part of the module) called
`$(internal:custom_visca_preset_selector)`

![Screenshot from 2022-09-16 19-11-25](https://user-images.githubusercontent.com/6708590/190692840-2c7ae619-ff6d-4bd6-bca5-dea976e7643d.png)

My workflow would use a button layout like this - the white field shows the number from the variable and + and - are used to modify the variable (using onboard companion Press Action "Value plus Value"
Line 1 and 3 are actions for my respective cameras (labeled in white)
e.g. pressing button 6.4 i would expect the currently selected "1" from my selector to be used as parameter "Preset Nr." in the Recall Preset Action.

![Screenshot from 2022-09-16 19-04-21](https://user-images.githubusercontent.com/6708590/190692765-bd5a2cad-b494-4d92-b8b6-75637cac1e6c.png)

Pressing 6.2 the current variable would increase to 11
Pressing 6.21 i would expect camera 2 to store it's current position to Preset 11

Considering that 0 and negative Preset numbers as well as >64 would be illegal parameters it would be best to incooperate the variable in the module and ensure it's altered accordingly e.g. 64+1 = 1 ...

**Comment by bensteUEM** [comment]
@goseid do you have any updates / considerations in regards to this request?

**Comment by goseid** [comment]
I'll play around with that a bit. It seems doable.

**Comment by goseid** [comment]
Your feature has been implemented @bensteUEM and should be merged into the beta soon.
