### ISSUE TITLE
Custom Commands

### ISSUE THREAD

**Issue by MrEm1** [bitfocus/companion-module-sony-visca#35]
Hi there, I am wondering if it would be possible to add the custom command functionality to the Sony VISCA module, similar to the PTZOptics Module.

**Comment by sonarkon** [comment]
would love this!

**Comment by tonsofpcs** [comment]
I would also like to see this, ideally an option for "raw" custom and one that includes the 0x8x for the selected camera.

**Comment by tonybeatle** [comment]
please add custom commands. I've been asking for so long. thanks

**Comment by goseid** [comment]
The Custom Command action has been implemented in Companion v3.0.0+5781 (beta).

**Comment by tonybeatle** [comment]
I'm trying to do a custom command to set the address of the cameras but its not letting put in the command code. The text is red and doesn't work. the command is 88 30 01 FF. What am I missing? Thanks

**Comment by goseid** [comment]
Is that the address set command? In the manual for my cameras it says "Not available for VISCA over IP".

"For VISCA network administration
• Address Set*
Sets an address of a peripheral device. Use
when initializing the network, and receiving the
following network change message.
* Not available for VISCA over IP."

In my experience valid custom commands work even if they are red. That indicates that it doesn't match what is expected but tries to send it anyway. Are you able to try other commands such as "81 01 06 06 10 FF"? That command should toggle the menu".

**Comment by mkotek** [comment]
Hi, I have received the AI related commands for [Tenveo PTZ NDI camera with 30x Optical Zoom](https://www.amazon.pl/dp/B0CNRQ4VGD).

Turn on auto framing | 自动框选所有人 | 81 0a 11 54 12 FF | 框选所有人并居中
turn on auto tracking | 选择人形 | 81 0a 11 54 02 FF | 选择人形然后自动跟踪
turn off auto tracking | 关闭人形选择 | 81 0a 11 54 03 FF | 关闭人形选择返回框选模式
Turn off auto framing | 关闭自动框选 | 81 0a 11 54 13 FF | 关闭自动框选和人形跟踪
Tracking left person | 选择人形左 | 81 0a 11 a3 02 FF |  
Tracking right person | 选择人形右 | 81 0a 11 a3 03 FF |  
OK | 选框消失 | 81 0a 11 a3 04 FF | 确定当前选择，选框消失

Can you implement them in the next version of the module?

**Comment by smartin1823** [comment]
Hello, could we add the new Sony BRC-AM7. I currently can't get them to work.

**Comment by OBLukas** [comment]
Hello! I am trying to send a custom command, but I can't seem to get it to work. I am using a Sony FR7. I see on the command list what the command is. For WHITE BALANCE, PRESET WHITE, DIRECT the template is "8x 01 05 43 0p 0r 0r 0r 0r FF". 

As far as I understand I the change the p to 1 for selecting the preset. Then the 4x r with the number I want the temperature to be. In my case it is 3200. I would assume that the command then would be: 8x 01 05 43 01 00 0C 08 00 FF

However it does not work. What am I doing wrong?

<img width="1614" alt="Image" src="https://github.com/user-attachments/assets/4fd30d1c-b199-499a-af86-5ca154c411da" />

**Comment by geraldlargaespada** [comment]
Tienes que cambiar también la “x” en secuencia tienes que probar:

81 01 05 43 01 00 01 05 0C 08 00 FF 
82 01 05 43 01 00 01 05 0C 08 00 FF 
83 01 05 43 01 00 01 05 0C 08 00 FF
.
.
Hasta que encuentres el segmento correcto.

Una vez que encuentres el segmento puedes probar los otros valores de “p” al menos así me pasó con las marshall.

**Comment by tom-niddatal** [comment]
Is it possible to implement  the following:

Most of the PTZ cameras do not save manaul set focus positions within the preset. So to store a manual focus I would like to make an inquiry to the camera which delivers the current focus position.
I the result could be stored in a variable, it would be possible to store this value wihtin companion and call it back when a certain preset is recalled.

For my camera (OBSBOT) 

FOCUS POSITION Inquiry =  81 09 04 48 FF 
REPLAY PACKET would be = y0 50 0p 0p 0p 0p FF | pppp: 0000 - 0064

It would be helpful then if the custom command would accept expressions i.e. a variable.


regards Tom

**Comment by geraldlargaespada** [comment]
recientemente termine de configurar mis camaras marshall, para algunas configuraciones utilice un software y poder ver lo que le llega y envia a traves de los puertos RS485 lo que la camara responde a cada comando que se le envia, en realidad no funciono tan bien como yo queria pero me dio una idea mas clara de como funciona.

busca el sscom5.13.1 software podras ver lo que la camara responde a cada comando que le envies.

les dejo mi post original de redit
https://www.reddit.com/user/Honest_Document1260/comments/1i3ztn9/stream_deck_y_companion_bitfocus_para_controlar/

**Comment by showem88** [comment]
For the Sony Visca - Some devices provide "Inquiry" data. For example, the Osbbot Tail 2 PTZ camera can be query'ed and it will return all sorts of data such as CAMERA POSITION. This can be extremely useful. 

See: https://www.obsbot.com/explore/obsbot-tail-air/visca-over-ip 

Can you add a command that sets a variable based on the response to a query/inquiry???   

((Note: This is basically similar to the request made by another user on 3-6-25 ))

There is a variable called "Last Command Sent". We need a variable "Reply Received" or something like this to show the response to an inquiry

**Comment by retrog-dev** [comment]
Is it possible to add the Zowietek AI commands? https://zowietek.com/knowledge-base/ai-ptz-camera/camera-setting-ai-ptz-camera/is-it-possible-to-setup-and-turn-on-or-off-tracking-by-visca-commands/?srsltid=AfmBOoqamBozGvydur1pPcCdi_OZ9yUkVRL-rkt6YyMU-vlLWYP6RdPY

**Comment by yasdfgr** [comment]
I have the same error:
`Module: Error executing action: e.viscaToString is not a function`
Can i do something on my own to resolve it?

Sony-visca 2.7.5
Companion 4.2.2

**Comment by Baysees** [comment]
Deploying a couple of Sony SRG-A12's and would love a command to turn auto tracking on/off

**Comment by NicholasZx** [comment]
<img width="1280" height="96" alt="Image" src="https://github.com/user-attachments/assets/88bbb1c2-e2ec-4949-89c0-6b82033d370b" />
81 0A 02 01 87 01 02 FF
81 0A 02 01 87 01 03 FF

for another camera.

your effort is much appreciated. kudos

**Comment by goseid** [comment]
@NicholasZx you should be able to use the custom command feature to implement that. As far as official actions, and presets we are focused on fully implementing the protocol for Sony cameras and are not trying to implement specific items for non sony cameras.
