### ISSUE TITLE
Sony 120DH Commands

### ISSUE THREAD

**Issue by sonarkon** [bitfocus/companion-module-sony-visca#36]
I have a Sony SRG 120DH and would like to work with some specific commands. Any chance that some of those get added?
I would be very grateful for those or some option to send custom commands. 

**Digital Zoom ON/OFF**
```
CAM_DZoomModeInq: 
Command Packet: 8x090406FF

D-Zoom On: y05002FF
D-Zoom Off: y05003FF

```

**Information Display**
```
Command Packet:  8x 097E 0118FF

On: y0 50 02 FF
Off: y05003FF

```

**The NR (Noise Reduction) function** removes noise (both random and non-random) to provide clearer images.
"This function has six steps: levels 1 to 5, plus off.
The NR effect is applied in levels based on the gain, and this setting value determines the limit of the effect. In bright conditions, changing the NR level will not have an effect."

`
CAM_NR
8x 01 04 53 0p FF // p: NR Setting (0: OFF, Level 1 to 5)
`

**Video Latency setting**
When the Video Latency is set to LOW, the latency until the shot image is output from the camera is shortened.

```
CAM_LowLatencyInq
Command Packet:  8x 097E 015AFF

Low: y0 50 02 FF
Normal: y0 50 03 FF
```

UDP Commands under:
https://pro.sony/support/res/manuals/AES7/81296da1a8a41043dc27edd9a72b7558/AES71001M.pdf

**Comment by goseid** [comment]
Those requests have been added to the module and should show up in the beta (Companion 3.x) as soon as they get merged into a new build.

My cameras don't have the low latency setting so I wasn't able to test that action. I did put in the command sequence from the link you provided so it is expected to work on cameras that do support it.
