### ISSUE TITLE
Custom Command errantly states that command does not start with "8"

### ISSUE THREAD

**Issue by rjurden** [bitfocus/companion-module-sony-visca#37]
I have the module set up and am attempting to use the custom command option. The custom command I am trying to use is 8x 01 04 35 02 FF.

The text in the field is red when setting up the command.

After testing the action, the log returns "Error, command "8x 01 04 35 02 FF" does not start with 8"

This is for version 2.4.1+4898-v2-4.1-9646192a

**Comment by goseid** [comment]
I'm not aware that this module sends custom commands. Are you using companion-module-sony-visca?

**Comment by goseid** [comment]
The custom command action has been implemented in Companion v3.0.0+5781 (beta). With this implementation you can begin the command with 80 or 81 or any valid hex command.
