### ISSUE TITLE
Sony Visca Over IP control byte incorrect

### ISSUE THREAD

**Issue by visionmill** [bitfocus/companion-module-sony-visca#4]
Sony Visca over IP module sends \x80 as the first byte in the command packet. This does not work with Lumens PTZ camera which supports Visca over IP.

Based on information here https://pro.sony/s3/cms-static-content/uploadfile/59/1237493025759.pdf the first byte should be between \x81 and \x87. \x88 is a broadcast byte. This byte represents the camera ID. In fact it states BRC-H900 locks this to \x81, although lumens cameras allow for full addressing.

I have modified the module code enough to test that changing the first byte to \x81 fixes the issue for lumens cameras set to address 1.

It would be really useful to have the ability to enter the camera ID in a dropdown when setting up the instance.

I've attached my modifications of the index.js file here.
[Visca Over IP Fix.zip](https://github.com/bitfocus/companion/files/3477868/Visca.Over.IP.Fix.zip)

**Desktop (please complete the following information):**
 - OS: 10.14.6
 - Browser Safari
 - Version 2.0.0

**Comment by JeffreyDavidsz** [comment]
This issue is transferred to a test Issue

**Comment by jpooley-hearst** [comment]
This may be an issue with BRC-H900 firmware previous to version 2.0

The BRC-X1000 manual is nearly identical and the X1000 works fine

I will update in a while once we send the BRC-H900 in to Sony to get chipped

**Comment by jpooley-hearst** [comment]
Firmware 2.10 for the BRC-H900 alleviates the aforementioned issue
