### ISSUE TITLE
Zoom speed command (if possible)

### ISSUE THREAD

**Issue by Gerrie12345** [bitfocus/companion-module-sony-visca#46]
Sony Visca V2.2.0 has a P/T speed command that does not have effect on the zoom speed.
There is no zoom speed command, has the zoom by default the lowest possible speed?

(the slow zoom buttons of the Sony IR remote control are a lot slower and ideal for cinematic effects)

**Comment by goseid** [comment]
This feature has been implemented in Companion v3.0.0+5781 (beta)

**Comment by Gerrie12345** [comment]
Thanks!

I tried to import my V3.0.0+5769 configuration in v3.0.0+5781, but that didn't work (all connections crasched).
Is that because the Sony Visca module has been updated and is that the case with every module update?
