### ISSUE TITLE
Add Start/Stop AutoTracking VISCA command for SRG-A40 cameras?

### ISSUE THREAD

**Issue by ero276** [bitfocus/companion-module-sony-visca#66]
Would love this VISCA command to be added so I could use the stream deck for this (like I use it for everything else video related) instead of the camera IP interface.

**Comment by thepoison606** [comment]
You could try sending a custom VISCA command from this table while the feature is not implemented. 

[https://pro.sony/support/res/manuals/5053/f48354480e724f0aef3d45d2e1eeab63/50531551M.pdf]

**Comment by ero276** [comment]
Send that command using the VISCA module? I didn’t see where there was an option for manual entry of commands… what am I missing?I thought about sending the VISCA command via UDP, but I can’t get the generic TCP/UDP  module to link to the camera, it just stays yellow “connecting” even with the correct port. Thanks for your help!Sent from my iPhoneOn Jan 8, 2024, at 3:17 AM, thepoison606 ***@***.***> wrote:﻿
You could try sending a custom VISCA command from this table while the feature is not implemented.
[https://pro.sony/support/res/manuals/5053/f48354480e724f0aef3d45d2e1eeab63/50531551M.pdf]

**Comment by thepoison606** [comment]
No, the VISCA module doesn't send http commands. Did you try the generic http? Or maybe even the "Website" Module from Elgato where you can select "Get-Request in Background" as an option.

**Comment by goseid** [comment]
Closing this issue since it is not supported in VISCA. If that changes we can readdress.
