### ISSUE TITLE
pan, tilt and zoom movement

### ISSUE THREAD

**Issue by frankleggett** [bitfocus/companion-module-sony-visca#9]
I installed the module on Saturday for a job and it worked first time. Is there a way to change the movement controls so they work on a hold down principle or even a toggle I am used to using Pan,Tilt and Zoom controls where they only operate if you hold down the button and this module moves the camera until you press a seperate stop button. Also is there a way to have a Speed Up and Down button I noticed you can set the speed but is there a way to put in a speed up and down?
Great work thanks.

**Comment by the1williegeorge** [comment]
Could you put the movement command in the Key Down section of a button and the stop command in the Key Up section?

**Comment by goseid** [comment]
I believe this functionality has been in place for a while but this issue never was closed. I'm closing it now.
